// Assuming this is in PropertyDetails.ts or similar
export interface PropertyDetails {
  property: {
    BedroomsTotal: number;
    ShowingInstructions: string;
    GreenWaterConservation: any[];
    CoolingYN: boolean;
    InsuranceExpense: number | null;
    RoomKitchenLevel: string | null;
    LotSizeUnits: string;
    MLSPIN_MARKET_TIME_BROKER: number;
    MLSPIN_LEVELS_1: number;
    LaundryFeatures: string[];
    Flooring: string[];
    RoomBathroom2Level: string | null;
    PhotosCount: number;
    FireplacesTotal: number;
    AdditionalParcelsYN: boolean | null;
    RoomBathroom1Area: number | null;
    WaterfrontFeatures: string[];
    MLSPIN_SQUARE_FEET_INCL_BASE: string;
    PastureArea: number | null;
    SubAgencyCompensation: number | null;
    MLSPIN_SOLD_VS_RENT: string | null;
    ViewYN: boolean | null;
    SeniorCommunityYN: boolean;
    Cooling: string[];
    GarageYN: boolean;
    ExteriorFeatures: string[];
    MLSPIN_TEAM_MEMBER: string | null;
    MLSPIN_SQUARE_FEET_OTHER: string | null;
    StatusChangeTimestamp: string;
    Longitude: number;
    AvailabilityDate: string | null;
    SecurityFeatures: string[];
    MLSPIN_DEQE: string | null;
    RoomBedroom2Level: string | null;
    DocumentsCount: number | null;
    PrivateOfficeRemarks: string;
    CarportYN: boolean | null;
    PublicRemarks: string;
    MLSPIN_SUB_AGENCY_OFFERED: string;
    MLSPIN_SELLER_DISCOUNT_PTS: number | null;
    FinancialDataSource: string[];
    BuildingName: string | null;
    AssociationFeeFrequency: string | null;
    CurrentFinancing: string[];
    MLSPIN_LEAD_PAINT: string[];
    RoomBedroom5Length: number | null;
    RoomBedroom4Area: number | null;
    MLSPIN_OFFLINE_LIST_NO: number;
    RoomDiningRoomWidth: number | null;
    HeatingYN: boolean;
    RoomBedroom3Features: string[];
    MLSPIN_MARKET_TIME_BROKER_PREV: number;
    MLSPIN_SQUARE_FEET_DISCLOSURES: string;
    PurchaseContractDate: string | null;
    RoadSurfaceType: string[];
    RoomDiningRoomFeatures: string[];
    ListingContractDate: string;
    MLSAreaMinor: string | null;
    FarmLandAreaUnits: string;
    RoomBathroom1Features: string[];
    Zoning: string;
    MLSPIN_MGF: string | null;
    MLSPIN_COMPLEX_COMPLETE: string | null;
    MLSPIN_MASTER_PAGE: string | null;
    GreenIndoorAirQuality: string[];
    MLSPIN_AUCTION_BUYERS_PREMIUM_PERCENT: number | null;
    Appliances: string[];
    MLSPIN_AvailableNow: string | null;
    MLSAreaMajor: string | null;
    TaxAnnualAmount: number;
    RoomKitchenWidth: number | null;
    TaxBlock: string | null;
    RoomBedroom4Length: number | null;
    RoomLivingRoomLength: number | null;
    MLSPIN_ENTERED_BY: string;
    MLSPIN_OH_FLAG: number;
    RoomBedroom2Features: string[];
    MLSPIN_DEPOSIT_REQD: string | null;
    MLSPIN_REQD_OWN_ASSOCIATION: string | null;
    Basement: string[];
    OriginatingSystemKey: string;
    BusinessType: string[];
    CountyOrParish: string;
    DualVariableCompensationYN: boolean | null;
    Latitude: number;
    MLSPIN_OPT_FEE_INCLUDES: string[];
    PropertyType: string;
    BathroomsTotalDecimal: number;
    PhotosChangeTimestamp: string;
    ListPrice: number;
    RoadFrontageType: string[];
    RoomBathroom2Area: number | null;
    RoomBedroom3Width: number | null;
    OriginatingSystemName: string;
    RoomBedroom2Width: number | null;
    RoomBathroom1Length: number | null;
    GreenEnergyGeneration: string[];
    AssociationYN: boolean | null;
    MlsStatus: string;
    FoundationArea: number | null;
    MLSPIN_SHOWINGS_DEFERRAL_DATE: string | null;
    RoomFamilyRoomLength: number | null;
    StreetNumber: string;
    GrossScheduledIncome: number | null;
    MLSPIN_FIRST_MON_REQD: string | null;
    ElectricExpense: number | null;
    MLSPIN_OWNER_OCC_SOURCE: string | null;
    MLSPIN_MARKET_TIME_PROPERTY_PREV: number;
    LeaseTerm: string | null;
    ListingKey: string;
    MLSPIN_RFS: string | null;
    RoomBedroom3Length: number | null;
    StateOrProvince: string;
    CommonWalls: string[];
    RoomBathroom3Width: number | null;
    MLSPIN_UNIT_BUILDING: string | null;
    RoomMasterBedroomFeatures: string[];
    CoveredSpaces: number;
    MiddleOrJuniorSchool: string | null;
    MLSPIN_MAIN_LO: string;
    AssociationFeeIncludes: string[];
    MLSPIN_MARKET_TIME_PROPERTY: number;
    SyndicateTo: string | null;
    RoomBedroom5Level: string | null;
    Gas: string[];
    MLSPIN_GRE: string | null;
    ElementarySchool: string | null;
    FrontageLength: string;
    MLSPIN_H_BTHS_1: number;
    MLSPIN_H_BTHS_2: number;
    MLSPIN_H_BTHS_3: number;
    MLSPIN_HTE: string | null;
    MLSPIN_H_BTHS_4: number | null;
    RoomBedroom2Length: number | null;
    MLSPIN_COOLING_UNITS: number;
    Disclosures: string[];
    RoomBathroom2Width: number | null;
    RoomBedroom4Level: string | null;
    RoomLivingRoomLevel: string | null;
    TaxMapNumber: string | null;
    FireplaceYN: boolean;
    Directions: string;
    MLSPIN_HOT_WATER: string[];
    MLSPIN_SyndicateToCurrentUser: boolean;
    BridgeModificationTimestamp: string;
    EntryLevel: string | null;
    YearBuiltEffective: string | null;
    AttachedGarageYN: boolean | null;
    RoomBedroom5Features: string[];
    MLSPIN_TITLE5: string | null;
    TaxBookNumber: string;
    MainLevelBathrooms: number | null;
    StandardStatus: string;
    CultivatedArea: number | null;
    MLSPIN_MASTER_BOOK: string | null;
    Roof: string[];
    RoomFamilyRoomLevel: string | null;
    PropertyCondition: string[];
    ParkingTotal: number;
    FrontageType: string[];
    DevelopmentStatus: string[];
    GrossIncome: number;
    ParcelNumber: string;
    PoolPrivateYN: boolean | null;
    AssociationFee: number | null;
    LotSizeSquareFeet: number;
    MLSPIN_DPR_Flag: string;
    TenantPays: string[];
    MLSPIN_MSE: string | null;
    MLSPIN_INSULATION_FEATURE: string[];
    Electric: string[];
    MLSPIN_RME: string | null;
    ArchitecturalStyle: string[];
    RoomMasterBathroomFeatures: string[];
    UnparsedAddress: string;
    MLSPIN_OPTIONAL_FEE: string | null;
    MLSPIN_COOLING_ZONES: number | null;
    WoodedArea: number | null;
    BuildingAreaTotal: number;
    TransactionBrokerCompensationType: string | null;
    YearBuiltSource: string;
    RoomFamilyRoomWidth: number | null;
    OtherEquipment: string[];
    MLSPIN_LAUNDRY_DIMEN: string | null;
    RoomFamilyRoomArea: number | null;
    FeedTypes: string[];
    url: string;
    Media: Array<any>;
  };
  agentName: string;
  officeName: string;
  zillowData: string[];
  message: string;
}
