import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/app/Footer/Footer'
import NavBar from '@/app/Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <head>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpH2-Av-Vx28bMqZaTA0VTTy7j1ffRvR0&libraries=places,geocoder"></script>
      </head>
      <NavBar/>
        <body className={inter.className}>{children}</body>
      <Footer/>
    </html>
  )
}
